version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"

  - package-ecosystem: "bun"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:10"
      timezone: "Europe/Paris"

  - package-ecosystem: "pub"
    directory: "/packages/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:20"
      timezone: "Europe/Paris"

  - package-ecosystem: "terraform"
    directory: "/packages/infrastructure/k8s"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Paris"

  - package-ecosystem: "terraform"
    directory: "/packages/infrastructure/aws"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:40"
      timezone: "Europe/Paris"

  - package-ecosystem: "terraform"
    directory: "/packages/infrastructure/init_backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:50"
      timezone: "Europe/Paris"
