apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: hollybike-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: Loic-Vanden-Bossche/hollybike-motoloup