name: Frontend CD

on:
  workflow_call:
    inputs:
      externall_call:
        description: 'To distinguish workflow_call from regular events'
        type: boolean
        required: false
        default: true
      version:
        description: 'Version of the release'
        type: string
        required: true
      image:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
        description: 'AWS Access Key ID'
      AWS_SECRET_ACCESS_KEY:
        required: false
        description: 'AWS Secret Access Key'

env:
  CI: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          echo ${{ inputs.version }}
          echo ${{ inputs.image }}

#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ vars.AWS_REGION }}
#
#      - name: Sync cacheable files with S3 bucket
#        run: aws s3 sync ./dist s3://${{ vars.AWS_S3_BUCKET }} --cache-control 'max-age=31536000' --exclude "*.html"
#
#      - name: Sync non cacheable files with S3 bucket
#        run: aws s3 sync ./dist s3://${{ vars.AWS_S3_BUCKET }} --cache-control 'no-cache'
#
#      - name: Create CloudFront invalidation
#        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_CF_DIST_ID }} --paths "/*"